/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

/**
 *
 * @author laura
 */
public class Credencial extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public Credencial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrincipal = new javax.swing.JPanel();
        PanelMenu = new javax.swing.JPanel();
        jlbLogo = new javax.swing.JLabel();
        jlbNomApp = new javax.swing.JLabel();
        bRespaldo = new javax.swing.JButton();
        bCerrar = new javax.swing.JButton();
        bHistorial = new javax.swing.JButton();
        bCredencial = new javax.swing.JButton();
        jlbImg1 = new javax.swing.JLabel();
        jlbIco = new javax.swing.JLabel();
        jlbTitulo2 = new javax.swing.JLabel();
        PanelDatos = new javax.swing.JPanel();
        jlbUsuario = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        sep2 = new javax.swing.JSeparator();
        jlbPlataforma = new javax.swing.JLabel();
        txtPlataforma = new javax.swing.JTextField();
        sep1 = new javax.swing.JSeparator();
        sep3 = new javax.swing.JSeparator();
        txtPassword = new javax.swing.JTextField();
        jlbPassword = new javax.swing.JLabel();
        sep4 = new javax.swing.JSeparator();
        txtURL = new javax.swing.JTextField();
        txtDatos = new javax.swing.JTextField();
        jlbDatos = new javax.swing.JLabel();
        jlbURL = new javax.swing.JLabel();
        jlbIco4 = new javax.swing.JLabel();
        jlbIco1 = new javax.swing.JLabel();
        jlbIco2 = new javax.swing.JLabel();
        jlbFecha = new javax.swing.JLabel();
        jlbActualizacion = new javax.swing.JLabel();
        bPrincipal = new javax.swing.JButton();
        bGuardar = new javax.swing.JButton();
        bEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SecurePass Manager");
        setResizable(false);

        PanelPrincipal.setBackground(new java.awt.Color(228, 233, 242));
        PanelPrincipal.setMinimumSize(new java.awt.Dimension(1024, 640));
        PanelPrincipal.setPreferredSize(new java.awt.Dimension(1024, 640));
        PanelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelMenu.setBackground(new java.awt.Color(31, 74, 125));
        PanelMenu.setPreferredSize(new java.awt.Dimension(230, 640));
        PanelMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlbLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/img6.png"))); // NOI18N
        PanelMenu.add(jlbLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, -1));

        jlbNomApp.setFont(new java.awt.Font("Roboto Flex", 1, 16)); // NOI18N
        jlbNomApp.setForeground(new java.awt.Color(255, 255, 255));
        jlbNomApp.setText("SecurePass Manager");
        PanelMenu.add(jlbNomApp, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        bRespaldo.setBackground(new java.awt.Color(31, 74, 125));
        bRespaldo.setFont(new java.awt.Font("Roboto Mono", 0, 16)); // NOI18N
        bRespaldo.setForeground(new java.awt.Color(255, 255, 255));
        bRespaldo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/respaldo.png"))); // NOI18N
        bRespaldo.setText(" Respaldo");
        bRespaldo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(63, 114, 175)));
        bRespaldo.setEnabled(false);
        bRespaldo.setPreferredSize(new java.awt.Dimension(145, 70));
        bRespaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRespaldoActionPerformed(evt);
            }
        });
        PanelMenu.add(bRespaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 230, 60));

        bCerrar.setBackground(new java.awt.Color(31, 74, 125));
        bCerrar.setFont(new java.awt.Font("Roboto Mono", 0, 16)); // NOI18N
        bCerrar.setForeground(new java.awt.Color(255, 255, 255));
        bCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/salir.png"))); // NOI18N
        bCerrar.setText(" Cerrar sesión");
        bCerrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(63, 114, 175)));
        bCerrar.setPreferredSize(new java.awt.Dimension(145, 70));
        bCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCerrarActionPerformed(evt);
            }
        });
        PanelMenu.add(bCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 230, 60));

        bHistorial.setBackground(new java.awt.Color(31, 74, 125));
        bHistorial.setFont(new java.awt.Font("Roboto Mono", 0, 16)); // NOI18N
        bHistorial.setForeground(new java.awt.Color(255, 255, 255));
        bHistorial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/historial.png"))); // NOI18N
        bHistorial.setText(" Historial");
        bHistorial.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(63, 114, 175)));
        bHistorial.setEnabled(false);
        bHistorial.setPreferredSize(new java.awt.Dimension(145, 70));
        bHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHistorialActionPerformed(evt);
            }
        });
        PanelMenu.add(bHistorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 230, 60));

        bCredencial.setBackground(new java.awt.Color(31, 74, 125));
        bCredencial.setFont(new java.awt.Font("Roboto Mono", 0, 16)); // NOI18N
        bCredencial.setForeground(new java.awt.Color(255, 255, 255));
        bCredencial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/look.png"))); // NOI18N
        bCredencial.setText(" Credenciales");
        bCredencial.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(63, 114, 175)));
        bCredencial.setPreferredSize(new java.awt.Dimension(145, 70));
        bCredencial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCredencialActionPerformed(evt);
            }
        });
        PanelMenu.add(bCredencial, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 230, 60));

        PanelPrincipal.add(PanelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 640));

        jlbImg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/img5.png"))); // NOI18N
        PanelPrincipal.add(jlbImg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, -1, -1));

        jlbIco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ban1.png"))); // NOI18N
        PanelPrincipal.add(jlbIco, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 30, -1, -1));

        jlbTitulo2.setBackground(new java.awt.Color(51, 51, 51));
        jlbTitulo2.setFont(new java.awt.Font("Roboto Flex", 0, 20)); // NOI18N
        jlbTitulo2.setText("Información de la credencial");
        PanelPrincipal.add(jlbTitulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 140, -1, -1));

        PanelDatos.setBackground(new java.awt.Color(185, 194, 210));
        PanelDatos.setPreferredSize(new java.awt.Dimension(448, 341));
        PanelDatos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlbUsuario.setBackground(new java.awt.Color(51, 51, 51));
        jlbUsuario.setFont(new java.awt.Font("Roboto Flex", 1, 16)); // NOI18N
        jlbUsuario.setText("Numero de Tarjeta");
        PanelDatos.add(jlbUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 140, -1));

        txtUsuario.setEditable(false);
        txtUsuario.setBackground(new java.awt.Color(185, 194, 210));
        txtUsuario.setFont(new java.awt.Font("Roboto Flex", 0, 15)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(51, 51, 51));
        txtUsuario.setText("Google");
        txtUsuario.setBorder(null);
        txtUsuario.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        PanelDatos.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 280, -1));

        sep2.setBackground(new java.awt.Color(228, 233, 242));
        sep2.setForeground(new java.awt.Color(228, 233, 242));
        PanelDatos.add(sep2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 450, 10));

        jlbPlataforma.setBackground(new java.awt.Color(51, 51, 51));
        jlbPlataforma.setFont(new java.awt.Font("Roboto Flex", 1, 16)); // NOI18N
        jlbPlataforma.setText("Banco");
        PanelDatos.add(jlbPlataforma, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 14, 90, -1));

        txtPlataforma.setEditable(false);
        txtPlataforma.setBackground(new java.awt.Color(185, 194, 210));
        txtPlataforma.setFont(new java.awt.Font("Roboto Flex", 0, 15)); // NOI18N
        txtPlataforma.setForeground(new java.awt.Color(51, 51, 51));
        txtPlataforma.setText("Google");
        txtPlataforma.setBorder(null);
        txtPlataforma.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtPlataforma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPlataformaActionPerformed(evt);
            }
        });
        PanelDatos.add(txtPlataforma, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 260, -1));

        sep1.setBackground(new java.awt.Color(228, 233, 242));
        sep1.setForeground(new java.awt.Color(228, 233, 242));
        PanelDatos.add(sep1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 450, 10));

        sep3.setBackground(new java.awt.Color(228, 233, 242));
        sep3.setForeground(new java.awt.Color(228, 233, 242));
        PanelDatos.add(sep3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 450, 10));

        txtPassword.setEditable(false);
        txtPassword.setBackground(new java.awt.Color(185, 194, 210));
        txtPassword.setFont(new java.awt.Font("Roboto Flex", 0, 15)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(51, 51, 51));
        txtPassword.setText("Google");
        txtPassword.setBorder(null);
        txtPassword.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        PanelDatos.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 280, -1));

        jlbPassword.setBackground(new java.awt.Color(51, 51, 51));
        jlbPassword.setFont(new java.awt.Font("Roboto Flex", 1, 16)); // NOI18N
        jlbPassword.setText("CVV");
        PanelDatos.add(jlbPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        sep4.setBackground(new java.awt.Color(228, 233, 242));
        sep4.setForeground(new java.awt.Color(228, 233, 242));
        PanelDatos.add(sep4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 450, 10));

        txtURL.setEditable(false);
        txtURL.setBackground(new java.awt.Color(185, 194, 210));
        txtURL.setFont(new java.awt.Font("Roboto Flex", 0, 15)); // NOI18N
        txtURL.setForeground(new java.awt.Color(51, 51, 51));
        txtURL.setText("Google");
        txtURL.setBorder(null);
        txtURL.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtURL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtURLActionPerformed(evt);
            }
        });
        PanelDatos.add(txtURL, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 280, -1));

        txtDatos.setEditable(false);
        txtDatos.setBackground(new java.awt.Color(185, 194, 210));
        txtDatos.setFont(new java.awt.Font("Roboto Flex", 0, 15)); // NOI18N
        txtDatos.setForeground(new java.awt.Color(51, 51, 51));
        txtDatos.setText("Google");
        txtDatos.setBorder(null);
        txtDatos.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDatosActionPerformed(evt);
            }
        });
        PanelDatos.add(txtDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 280, -1));

        jlbDatos.setBackground(new java.awt.Color(51, 51, 51));
        jlbDatos.setFont(new java.awt.Font("Roboto Flex", 1, 16)); // NOI18N
        jlbDatos.setText("Datos extra");
        PanelDatos.add(jlbDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 90, -1));

        jlbURL.setBackground(new java.awt.Color(51, 51, 51));
        jlbURL.setFont(new java.awt.Font("Roboto Flex", 1, 16)); // NOI18N
        jlbURL.setText("Fecha de caducidad");
        PanelDatos.add(jlbURL, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jlbIco4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/editar.png"))); // NOI18N
        PanelDatos.add(jlbIco4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 310, -1, -1));

        jlbIco1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/eyeOff1.png"))); // NOI18N
        PanelDatos.add(jlbIco1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, -1, -1));

        jlbIco2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/eyeOff1.png"))); // NOI18N
        PanelDatos.add(jlbIco2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, -1, -1));

        PanelPrincipal.add(PanelDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, -1, 350));

        jlbFecha.setBackground(new java.awt.Color(51, 51, 51));
        jlbFecha.setFont(new java.awt.Font("Roboto Flex", 0, 16)); // NOI18N
        jlbFecha.setText("Fecha de Actualización");
        PanelPrincipal.add(jlbFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 590, 170, -1));

        jlbActualizacion.setBackground(new java.awt.Color(51, 51, 51));
        jlbActualizacion.setFont(new java.awt.Font("Roboto Flex", 0, 16)); // NOI18N
        jlbActualizacion.setText("Actualizado :");
        PanelPrincipal.add(jlbActualizacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 590, 100, -1));

        bPrincipal.setBackground(new java.awt.Color(185, 194, 210));
        bPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/principal.png"))); // NOI18N
        bPrincipal.setPreferredSize(new java.awt.Dimension(60, 68));
        PanelPrincipal.add(bPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 350, -1, -1));

        bGuardar.setBackground(new java.awt.Color(185, 194, 210));
        bGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/guardarCam.png"))); // NOI18N
        bGuardar.setPreferredSize(new java.awt.Dimension(60, 68));
        PanelPrincipal.add(bGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 210, -1, -1));

        bEliminar.setBackground(new java.awt.Color(185, 194, 210));
        bEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/eliminar.png"))); // NOI18N
        bEliminar.setPreferredSize(new java.awt.Dimension(60, 68));
        PanelPrincipal.add(bEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 280, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 1030, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bRespaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRespaldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bRespaldoActionPerformed

    private void bCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCerrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bCerrarActionPerformed

    private void bHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHistorialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bHistorialActionPerformed

    private void bCredencialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCredencialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bCredencialActionPerformed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void txtPlataformaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPlataformaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPlataformaActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void txtURLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtURLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtURLActionPerformed

    private void txtDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDatosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDatosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Credencial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Credencial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Credencial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Credencial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Credencial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelDatos;
    private javax.swing.JPanel PanelMenu;
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JButton bCerrar;
    private javax.swing.JButton bCredencial;
    private javax.swing.JButton bEliminar;
    private javax.swing.JButton bGuardar;
    private javax.swing.JButton bHistorial;
    private javax.swing.JButton bPrincipal;
    private javax.swing.JButton bRespaldo;
    private javax.swing.JLabel jlbActualizacion;
    private javax.swing.JLabel jlbDatos;
    private javax.swing.JLabel jlbFecha;
    private javax.swing.JLabel jlbIco;
    private javax.swing.JLabel jlbIco1;
    private javax.swing.JLabel jlbIco2;
    private javax.swing.JLabel jlbIco4;
    private javax.swing.JLabel jlbImg1;
    private javax.swing.JLabel jlbLogo;
    private javax.swing.JLabel jlbNomApp;
    private javax.swing.JLabel jlbPassword;
    private javax.swing.JLabel jlbPlataforma;
    private javax.swing.JLabel jlbTitulo2;
    private javax.swing.JLabel jlbURL;
    private javax.swing.JLabel jlbUsuario;
    private javax.swing.JSeparator sep1;
    private javax.swing.JSeparator sep2;
    private javax.swing.JSeparator sep3;
    private javax.swing.JSeparator sep4;
    private javax.swing.JTextField txtDatos;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtPlataforma;
    private javax.swing.JTextField txtURL;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
