/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

/**
 *
 * @author laura
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrincipal = new javax.swing.JPanel();
        txtBuscar = new javax.swing.JTextField();
        jlbIco1 = new javax.swing.JLabel();
        jspTabla = new javax.swing.JScrollPane();
        jTLista = new javax.swing.JTable();
        PanelFiltro = new javax.swing.JPanel();
        jlbTituloF = new javax.swing.JLabel();
        jcbCorreo = new javax.swing.JComboBox<>();
        jcbPlataforma = new javax.swing.JComboBox<>();
        jcbBanco = new javax.swing.JComboBox<>();
        PanelMenu = new javax.swing.JPanel();
        jlbLogo = new javax.swing.JLabel();
        jlbNomApp = new javax.swing.JLabel();
        bRespaldo = new javax.swing.JButton();
        bCerrar = new javax.swing.JButton();
        bHistorial = new javax.swing.JButton();
        bCredencial = new javax.swing.JButton();
        jlbImg1 = new javax.swing.JLabel();
        bBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SecurePass Manager");
        setResizable(false);

        PanelPrincipal.setBackground(new java.awt.Color(249, 247, 247));
        PanelPrincipal.setMinimumSize(new java.awt.Dimension(1024, 640));
        PanelPrincipal.setPreferredSize(new java.awt.Dimension(1024, 640));
        PanelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtBuscar.setFont(new java.awt.Font("Roboto Mono", 0, 15)); // NOI18N
        txtBuscar.setForeground(new java.awt.Color(102, 102, 102));
        txtBuscar.setText("Buscar");
        txtBuscar.setPreferredSize(new java.awt.Dimension(338, 40));
        PanelPrincipal.add(txtBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, -1, -1));

        jlbIco1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/buscar.png"))); // NOI18N
        PanelPrincipal.add(jlbIco1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, -1, -1));

        jspTabla.setBorder(null);
        jspTabla.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N

        jTLista.setBackground(new java.awt.Color(249, 247, 247));
        jTLista.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jTLista.setForeground(new java.awt.Color(51, 51, 51));
        jTLista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jspTabla.setViewportView(jTLista);

        PanelPrincipal.add(jspTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, 450, 430));

        PanelFiltro.setBackground(new java.awt.Color(222, 225, 232));
        PanelFiltro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlbTituloF.setFont(new java.awt.Font("Roboto", 1, 16)); // NOI18N
        jlbTituloF.setForeground(new java.awt.Color(30, 30, 30));
        jlbTituloF.setText("Filtrar por");
        PanelFiltro.add(jlbTituloF, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jcbCorreo.setBackground(new java.awt.Color(222, 225, 232));
        jcbCorreo.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        jcbCorreo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Correo electrónico" }));
        jcbCorreo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelFiltro.add(jcbCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 210, 50));

        jcbPlataforma.setBackground(new java.awt.Color(222, 225, 232));
        jcbPlataforma.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        jcbPlataforma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Plataforma" }));
        jcbPlataforma.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelFiltro.add(jcbPlataforma, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 210, 50));

        jcbBanco.setBackground(new java.awt.Color(222, 225, 232));
        jcbBanco.setFont(new java.awt.Font("Roboto", 0, 15)); // NOI18N
        jcbBanco.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Banco" }));
        jcbBanco.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelFiltro.add(jcbBanco, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 210, 50));

        PanelPrincipal.add(PanelFiltro, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 170, 230, 250));

        PanelMenu.setBackground(new java.awt.Color(31, 74, 125));
        PanelMenu.setPreferredSize(new java.awt.Dimension(230, 640));
        PanelMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlbLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/img6.png"))); // NOI18N
        PanelMenu.add(jlbLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, -1));

        jlbNomApp.setFont(new java.awt.Font("Roboto Flex", 1, 16)); // NOI18N
        jlbNomApp.setForeground(new java.awt.Color(255, 255, 255));
        jlbNomApp.setText("SecurePass Manager");
        PanelMenu.add(jlbNomApp, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        bRespaldo.setBackground(new java.awt.Color(31, 74, 125));
        bRespaldo.setFont(new java.awt.Font("Roboto Mono", 0, 16)); // NOI18N
        bRespaldo.setForeground(new java.awt.Color(255, 255, 255));
        bRespaldo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/respaldo.png"))); // NOI18N
        bRespaldo.setText(" Respaldo");
        bRespaldo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(63, 114, 175)));
        bRespaldo.setEnabled(false);
        bRespaldo.setPreferredSize(new java.awt.Dimension(145, 70));
        bRespaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRespaldoActionPerformed(evt);
            }
        });
        PanelMenu.add(bRespaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 230, 60));

        bCerrar.setBackground(new java.awt.Color(31, 74, 125));
        bCerrar.setFont(new java.awt.Font("Roboto Mono", 0, 16)); // NOI18N
        bCerrar.setForeground(new java.awt.Color(255, 255, 255));
        bCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/salir.png"))); // NOI18N
        bCerrar.setText(" Cerrar sesión");
        bCerrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(63, 114, 175)));
        bCerrar.setPreferredSize(new java.awt.Dimension(145, 70));
        bCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCerrarActionPerformed(evt);
            }
        });
        PanelMenu.add(bCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 230, 60));

        bHistorial.setBackground(new java.awt.Color(31, 74, 125));
        bHistorial.setFont(new java.awt.Font("Roboto Mono", 0, 16)); // NOI18N
        bHistorial.setForeground(new java.awt.Color(255, 255, 255));
        bHistorial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/historial.png"))); // NOI18N
        bHistorial.setText(" Historial");
        bHistorial.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(63, 114, 175)));
        bHistorial.setEnabled(false);
        bHistorial.setPreferredSize(new java.awt.Dimension(145, 70));
        bHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHistorialActionPerformed(evt);
            }
        });
        PanelMenu.add(bHistorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 230, 60));

        bCredencial.setBackground(new java.awt.Color(31, 74, 125));
        bCredencial.setFont(new java.awt.Font("Roboto Mono", 0, 16)); // NOI18N
        bCredencial.setForeground(new java.awt.Color(255, 255, 255));
        bCredencial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/look.png"))); // NOI18N
        bCredencial.setText(" Credenciales");
        bCredencial.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(63, 114, 175)));
        bCredencial.setPreferredSize(new java.awt.Dimension(145, 70));
        bCredencial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCredencialActionPerformed(evt);
            }
        });
        PanelMenu.add(bCredencial, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 230, 60));

        PanelPrincipal.add(PanelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 640));

        jlbImg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/img5.png"))); // NOI18N
        PanelPrincipal.add(jlbImg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, -1, -1));

        bBuscar.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        bBuscar.setText("BUSCAR");
        bBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        PanelPrincipal.add(bBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 70, 100, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 1030, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bRespaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRespaldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bRespaldoActionPerformed

    private void bCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCerrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bCerrarActionPerformed

    private void bHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHistorialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bHistorialActionPerformed

    private void bCredencialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCredencialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bCredencialActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelFiltro;
    private javax.swing.JPanel PanelMenu;
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JButton bBuscar;
    private javax.swing.JButton bCerrar;
    private javax.swing.JButton bCredencial;
    private javax.swing.JButton bHistorial;
    private javax.swing.JButton bRespaldo;
    private javax.swing.JTable jTLista;
    private javax.swing.JComboBox<String> jcbBanco;
    private javax.swing.JComboBox<String> jcbCorreo;
    private javax.swing.JComboBox<String> jcbPlataforma;
    private javax.swing.JLabel jlbIco1;
    private javax.swing.JLabel jlbImg1;
    private javax.swing.JLabel jlbLogo;
    private javax.swing.JLabel jlbNomApp;
    private javax.swing.JLabel jlbTituloF;
    private javax.swing.JScrollPane jspTabla;
    private javax.swing.JTextField txtBuscar;
    // End of variables declaration//GEN-END:variables
}
