/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

/**
 *
 * @author laura
 */
public class viewCredencial extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public viewCredencial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelPrincipal = new javax.swing.JPanel();
        PanelMenu = new javax.swing.JPanel();
        jlbLogo = new javax.swing.JLabel();
        jlbNomApp = new javax.swing.JLabel();
        bRespaldo = new javax.swing.JButton();
        bCerrar = new javax.swing.JButton();
        bHistorial = new javax.swing.JButton();
        bCredencial = new javax.swing.JButton();
        jlbImg1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        URL1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        URL = new javax.swing.JLabel();
        URL2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SecurePass Manager");
        setResizable(false);

        PanelPrincipal.setBackground(new java.awt.Color(228, 233, 242));
        PanelPrincipal.setMinimumSize(new java.awt.Dimension(1024, 640));
        PanelPrincipal.setPreferredSize(new java.awt.Dimension(1024, 640));
        PanelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelMenu.setBackground(new java.awt.Color(31, 74, 125));
        PanelMenu.setPreferredSize(new java.awt.Dimension(230, 640));
        PanelMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlbLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/img6.png"))); // NOI18N
        PanelMenu.add(jlbLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, -1));

        jlbNomApp.setFont(new java.awt.Font("Roboto Flex", 1, 16)); // NOI18N
        jlbNomApp.setForeground(new java.awt.Color(255, 255, 255));
        jlbNomApp.setText("SecurePass Manager");
        PanelMenu.add(jlbNomApp, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        bRespaldo.setBackground(new java.awt.Color(31, 74, 125));
        bRespaldo.setFont(new java.awt.Font("Roboto Mono", 0, 16)); // NOI18N
        bRespaldo.setForeground(new java.awt.Color(255, 255, 255));
        bRespaldo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/respaldo.png"))); // NOI18N
        bRespaldo.setText(" Respaldo");
        bRespaldo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(63, 114, 175)));
        bRespaldo.setEnabled(false);
        bRespaldo.setPreferredSize(new java.awt.Dimension(145, 70));
        bRespaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRespaldoActionPerformed(evt);
            }
        });
        PanelMenu.add(bRespaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 230, 60));

        bCerrar.setBackground(new java.awt.Color(31, 74, 125));
        bCerrar.setFont(new java.awt.Font("Roboto Mono", 0, 16)); // NOI18N
        bCerrar.setForeground(new java.awt.Color(255, 255, 255));
        bCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/salir.png"))); // NOI18N
        bCerrar.setText(" Cerrar sesión");
        bCerrar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(63, 114, 175)));
        bCerrar.setPreferredSize(new java.awt.Dimension(145, 70));
        bCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCerrarActionPerformed(evt);
            }
        });
        PanelMenu.add(bCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 230, 60));

        bHistorial.setBackground(new java.awt.Color(31, 74, 125));
        bHistorial.setFont(new java.awt.Font("Roboto Mono", 0, 16)); // NOI18N
        bHistorial.setForeground(new java.awt.Color(255, 255, 255));
        bHistorial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/historial.png"))); // NOI18N
        bHistorial.setText(" Historial");
        bHistorial.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(63, 114, 175)));
        bHistorial.setEnabled(false);
        bHistorial.setPreferredSize(new java.awt.Dimension(145, 70));
        bHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bHistorialActionPerformed(evt);
            }
        });
        PanelMenu.add(bHistorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 230, 60));

        bCredencial.setBackground(new java.awt.Color(31, 74, 125));
        bCredencial.setFont(new java.awt.Font("Roboto Mono", 0, 16)); // NOI18N
        bCredencial.setForeground(new java.awt.Color(255, 255, 255));
        bCredencial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/look.png"))); // NOI18N
        bCredencial.setText(" Credenciales");
        bCredencial.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(63, 114, 175)));
        bCredencial.setPreferredSize(new java.awt.Dimension(145, 70));
        bCredencial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCredencialActionPerformed(evt);
            }
        });
        PanelMenu.add(bCredencial, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 230, 60));

        PanelPrincipal.add(PanelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 640));

        jlbImg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/img5.png"))); // NOI18N
        PanelPrincipal.add(jlbImg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/plat1.png"))); // NOI18N
        PanelPrincipal.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 30, -1, -1));

        jLabel2.setBackground(new java.awt.Color(51, 51, 51));
        jLabel2.setFont(new java.awt.Font("Roboto Flex", 0, 20)); // NOI18N
        jLabel2.setText("Información de la credencial");
        PanelPrincipal.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 140, -1, -1));

        jPanel1.setBackground(new java.awt.Color(185, 194, 210));
        jPanel1.setPreferredSize(new java.awt.Dimension(448, 341));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(51, 51, 51));
        jLabel3.setFont(new java.awt.Font("Roboto Flex", 1, 16)); // NOI18N
        jLabel3.setText("Usuario");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 60, -1));

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(185, 194, 210));
        jTextField1.setFont(new java.awt.Font("Roboto Flex", 0, 15)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(51, 51, 51));
        jTextField1.setText("Google");
        jTextField1.setBorder(null);
        jTextField1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 280, -1));

        jSeparator1.setBackground(new java.awt.Color(228, 233, 242));
        jSeparator1.setForeground(new java.awt.Color(228, 233, 242));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 450, 10));

        jLabel4.setBackground(new java.awt.Color(51, 51, 51));
        jLabel4.setFont(new java.awt.Font("Roboto Flex", 1, 16)); // NOI18N
        jLabel4.setText("Plataforma");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 14, 90, -1));

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(185, 194, 210));
        jTextField2.setFont(new java.awt.Font("Roboto Flex", 0, 15)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(51, 51, 51));
        jTextField2.setText("Google");
        jTextField2.setBorder(null);
        jTextField2.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 260, -1));

        jSeparator2.setBackground(new java.awt.Color(228, 233, 242));
        jSeparator2.setForeground(new java.awt.Color(228, 233, 242));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 450, 10));

        jSeparator3.setBackground(new java.awt.Color(228, 233, 242));
        jSeparator3.setForeground(new java.awt.Color(228, 233, 242));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 450, 10));

        jTextField3.setEditable(false);
        jTextField3.setBackground(new java.awt.Color(185, 194, 210));
        jTextField3.setFont(new java.awt.Font("Roboto Flex", 0, 15)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(51, 51, 51));
        jTextField3.setText("Google");
        jTextField3.setBorder(null);
        jTextField3.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 280, -1));

        jLabel5.setBackground(new java.awt.Color(51, 51, 51));
        jLabel5.setFont(new java.awt.Font("Roboto Flex", 1, 16)); // NOI18N
        jLabel5.setText("Contraseña");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 90, -1));

        jSeparator4.setBackground(new java.awt.Color(228, 233, 242));
        jSeparator4.setForeground(new java.awt.Color(228, 233, 242));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 450, 10));

        jTextField4.setEditable(false);
        jTextField4.setBackground(new java.awt.Color(185, 194, 210));
        jTextField4.setFont(new java.awt.Font("Roboto Flex", 0, 15)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(51, 51, 51));
        jTextField4.setText("Google");
        jTextField4.setBorder(null);
        jTextField4.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 280, -1));

        jTextField5.setEditable(false);
        jTextField5.setBackground(new java.awt.Color(185, 194, 210));
        jTextField5.setFont(new java.awt.Font("Roboto Flex", 0, 15)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(51, 51, 51));
        jTextField5.setText("Google");
        jTextField5.setBorder(null);
        jTextField5.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 280, -1));

        jLabel7.setBackground(new java.awt.Color(51, 51, 51));
        jLabel7.setFont(new java.awt.Font("Roboto Flex", 1, 16)); // NOI18N
        jLabel7.setText("Datos extra");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 90, -1));

        URL1.setBackground(new java.awt.Color(51, 51, 51));
        URL1.setFont(new java.awt.Font("Roboto Flex", 1, 16)); // NOI18N
        URL1.setText("URL");
        jPanel1.add(URL1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 40, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/editar.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 310, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/editar.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/editar.png"))); // NOI18N
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, -1, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/editar.png"))); // NOI18N
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, -1, -1));

        PanelPrincipal.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, -1, 350));

        URL.setBackground(new java.awt.Color(51, 51, 51));
        URL.setFont(new java.awt.Font("Roboto Flex", 0, 16)); // NOI18N
        URL.setText("Fecha de Actualización");
        PanelPrincipal.add(URL, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 590, 170, -1));

        URL2.setBackground(new java.awt.Color(51, 51, 51));
        URL2.setFont(new java.awt.Font("Roboto Flex", 0, 16)); // NOI18N
        URL2.setText("Actualizado :");
        PanelPrincipal.add(URL2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 590, 100, -1));

        jButton2.setBackground(new java.awt.Color(185, 194, 210));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/principal.png"))); // NOI18N
        jButton2.setPreferredSize(new java.awt.Dimension(60, 68));
        PanelPrincipal.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 350, -1, -1));

        jButton3.setBackground(new java.awt.Color(185, 194, 210));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/guardarCam.png"))); // NOI18N
        jButton3.setPreferredSize(new java.awt.Dimension(60, 68));
        PanelPrincipal.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 210, -1, -1));

        jButton4.setBackground(new java.awt.Color(185, 194, 210));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/eliminar.png"))); // NOI18N
        jButton4.setPreferredSize(new java.awt.Dimension(60, 68));
        PanelPrincipal.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 280, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 1030, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bRespaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRespaldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bRespaldoActionPerformed

    private void bCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCerrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bCerrarActionPerformed

    private void bHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bHistorialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bHistorialActionPerformed

    private void bCredencialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCredencialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bCredencialActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewCredencial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewCredencial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewCredencial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewCredencial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewCredencial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelMenu;
    private javax.swing.JPanel PanelPrincipal;
    private javax.swing.JLabel URL;
    private javax.swing.JLabel URL1;
    private javax.swing.JLabel URL2;
    private javax.swing.JButton bCerrar;
    private javax.swing.JButton bCredencial;
    private javax.swing.JButton bHistorial;
    private javax.swing.JButton bRespaldo;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JLabel jlbImg1;
    private javax.swing.JLabel jlbLogo;
    private javax.swing.JLabel jlbNomApp;
    // End of variables declaration//GEN-END:variables
}
