USE SecurePassManagerDB;

# Tabla: T_USUARIOS
CREATE TABLE IF NOT EXISTS T_USUARIOS(
  PK_Nombre_Usuario VARCHAR(15) NOT NULL,
  Password VARCHAR(150) NOT NULL,
  Nombre_Usuario_Titular VARCHAR(30) NOT NULL,
  AP_PAT VARCHAR(15) NOT NULL,
  AP_MAT VARCHAR(15) NOT NULL,

	PRIMARY KEY (PK_Nombre_Usuario)
);

# Tabla: T_CREEDENCIALES
CREATE TABLE IF NOT EXISTS T_CREDENCIALES(
  ID_Credencial INT(3) AUTO_INCREMENT NOT NULL,
  Nombre_Plataforma VARCHAR(30) NOT NULL,
  Usuario_Web VARCHAR(30) NOT NULL,
  URL VARCHAR(30) NOT NULL,
  Password VARCHAR(150) NOT NULL,
  Fecha_Alta DATETIME DEFAULT NOW() NOT NULL,
  Fecha_Update DATETIME DEFAULT NOW() NOT NULL,
  Extra VARCHAR(120),
  FK_Nombre_Usuario VARCHAR(15) NOT NULL,

  PRIMARY KEY (ID_Credencial),
	FOREIGN KEY (FK_Nombre_Usuario) REFERENCES T_USUARIOS(PK_Nombre_Usuario) ON DELETE CASCADE ON UPDATE CASCADE
);

# Tabla: T_CREDENCIALES_BANCARIAS
CREATE TABLE IF NOT EXISTS T_CREDENCIALES_BANCARIAS(
  ID_Credencial_Bancaria INT(3) AUTO_INCREMENT NOT NULL,
  Nombre_Banco VARCHAR(30) NOT NULL,
  Numero_Tarjeta CHAR(16) NOT NULL,
  CVV VARCHAR(150) NOT NULL,
  Fecha_Caducidad DATETIME NOT NULL,
  Fecha_Alta DATETIME DEFAULT NOW() NOT NULL,
  Fecha_Update DATETIME DEFAULT NOW() NOT NULL,
  Extra VARCHAR(120),
  FK_Nombre_Usuario VARCHAR(15) NOT NULL,

  PRIMARY KEY (ID_Credencial_Bancaria),
  FOREIGN KEY (FK_Nombre_Usuario) REFERENCES T_USUARIOS(PK_Nombre_Usuario) ON DELETE CASCADE ON UPDATE CASCADE
);
