USE SecurePassManagerDB;

DROP TABLE IF EXISTS T_CREDENCIALES_BANCARIAS;
DROP TABLE IF EXISTS T_CREDENCIALES;
DROP TABLE IF EXISTS T_USUARIOS;

-- DROP USER IF EXISTS SecurePassManager@localhost;

DROP DATABASE IF EXISTS SecurePassManagerDB;
